### ISSUE TITLE
What license is it for this repo?

### ISSUE THREAD

**Issue by andyboo410** [cvlab-epfl/EPnP#3]
Is it possible you could provide MIT or BSD license on you github page so I can download it for evaluation? Do I have permission of downloading and using your code to generate results?

Thanks
Andy

**Comment by adynathos** [comment]
Hello,
I am not the author of the code.
The authors are not looking at the repo so if you need complete reassurance, they would need to be contacted by other channels.

**Comment by andyboo410** [comment]
Hi
Thanks for the reply.
Do you by any chance at all know how I can contact the authors? I don't see e-mail listed anywhere.

**Comment by adynathos** [comment]
The authors have decided on a CC NonCommercial license:
https://creativecommons.org/licenses/by-nc-sa/4.0/
